### ISSUE TITLE
Implement user-level, professor-level card ownerships

### ISSUE THREAD

**Issue by johnserraon** [rainbow-cards/manoa-rainbow-cards#58]
Do all work for this task in a branch called issue-58

- May first need to make sure new user accounts are properly recorded in database.
- Add ownership capability to cards, linking them to **users** (e.g., by user ID) and **professors**

**Comment by mizu-benrb** [comment]
Duplicates of cards will be instantiated separately, owned by different users. Professor-email should also be tracked by a card.
